USE [master]
GO

/****** Object:  Database [Shaa]    Script Date: 10/20/2022 12:43:51 PM ******/
CREATE DATABASE [Shaa]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Sha', FILENAME = N'E:\Database\Shaa\Sha.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Sha_log', FILENAME = N'E:\Database\Shaa\Sha_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Shaa].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Shaa] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Shaa] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Shaa] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Shaa] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Shaa] SET ARITHABORT OFF 
GO

ALTER DATABASE [Shaa] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Shaa] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Shaa] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Shaa] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Shaa] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Shaa] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Shaa] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Shaa] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Shaa] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Shaa] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Shaa] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Shaa] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Shaa] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Shaa] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Shaa] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Shaa] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Shaa] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Shaa] SET RECOVERY FULL 
GO

ALTER DATABASE [Shaa] SET  MULTI_USER 
GO

ALTER DATABASE [Shaa] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Shaa] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Shaa] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Shaa] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Shaa] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Shaa] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Shaa] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Shaa] SET  READ_WRITE 
GO


/****** Object:  Table [dbo].[User]    Script Date: 10/20/2022 12:44:20 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[User](
	[Id] [UNIQUEIDENTIFIER] NOT NULL,
	[FirstName] [NVARCHAR](50) NOT NULL,
	[LastName] [NVARCHAR](50) NOT NULL,
	[PhoneNumber] [VARCHAR](11) NULL,
	[Email] [VARCHAR](50) NULL,
	[NationalNo] [NVARCHAR](50) NOT NULL,
	[Description] [NVARCHAR](4000) NULL,
	[Password] [VARCHAR](255) NOT NULL,
	[BirthDate] [DATETIME] NULL,
	[CountryId] [INT] NULL,
	[CityId] [INT] NULL,
	[IsEmailConfirmed] [BIT] NOT NULL,
	[IsAdmin] [BIT] NOT NULL,
	[IsBanned] [BIT] NOT NULL,
	[EmailActivationCode] [VARCHAR](255) NULL,
	[DepartmentId] [UNIQUEIDENTIFIER] NULL,
	[IsDeleted] [BIT] NULL,
	[CreationDate] [DATETIME] NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [Lab].[Ability]    Script Date: 10/20/2022 12:44:59 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Lab].[Ability](
	[Id] [UNIQUEIDENTIFIER] NOT NULL,
	[Title] [NVARCHAR](255) NOT NULL,
	[LaboratoryId] [UNIQUEIDENTIFIER] NOT NULL,
	[FurtherDetailsAndProcedure] [NVARCHAR](1000) NULL,
	[DescriptionOfConsumables] [NVARCHAR](1000) NULL,
	[ConsumableCost] [BIGINT] NULL,
	[HumanResourceCost] [BIGINT] NULL,
	[OtherCost] [BIGINT] NULL,
	[ImplementationCost] [BIGINT] NULL,
	[ImplementationTime] [DATETIME] NULL,
	[FileAttachment] [VARCHAR](255) NULL,
 CONSTRAINT [PK_Ability] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [Lab].[Equipment]    Script Date: 10/20/2022 12:45:24 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Lab].[Equipment](
	[Id] [UNIQUEIDENTIFIER] NOT NULL,
	[LaboratoryId] [UNIQUEIDENTIFIER] NOT NULL,
	[EquipmentTypeId] [INT] NOT NULL,
	[Title] [NVARCHAR](255) NOT NULL,
	[UsageTypeId] [INT] NOT NULL,
	[CountryId] [INT] NULL,
	[CompanyName] [NVARCHAR](255) NULL,
	[Model] [VARCHAR](100) NULL,
	[SerialNumber] [VARCHAR](100) NULL,
	[InstallationDate] [DATETIME] NULL,
	[ExploitationDate] [DATETIME] NULL,
	[SupplyTypeId] [INT] NULL,
	[WardId] [UNIQUEIDENTIFIER] NULL,
	[EquipmentCost] [BIGINT] NULL,
 CONSTRAINT [PK_Equipment] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [Lab].[EquipmentAbility]    Script Date: 10/20/2022 12:45:52 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Lab].[EquipmentAbility](
	[Id] [BIGINT] IDENTITY(1,1) NOT NULL,
	[AbilityId] [UNIQUEIDENTIFIER] NOT NULL,
	[EquipmentId] [UNIQUEIDENTIFIER] NOT NULL,
 CONSTRAINT [PK_EquipmentAbility] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [Lab].[Laboratory]    Script Date: 10/20/2022 12:46:16 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Lab].[Laboratory](
	[Id] [UNIQUEIDENTIFIER] NOT NULL,
	[Title] [NVARCHAR](255) NOT NULL,
	[LaboratoryTypeId] [INT] NOT NULL,
	[PassiveDefenceId] [INT] NOT NULL,
	[ApprovalAuthorityId] [INT] NULL,
	[ResearchCenterId] [UNIQUEIDENTIFIER] NULL,
	[StandardStatusId] [INT] NULL,
	[PhoneNumber] [VARCHAR](15) NULL,
	[ImagePath] [NVARCHAR](1000) NULL,
	[Address] [NVARCHAR](4000) NULL,
	[Description] [NVARCHAR](4000) NULL,
 CONSTRAINT [PK_Laboratory] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [Lab].[Ward]    Script Date: 10/20/2022 12:46:45 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Lab].[Ward](
	[Id] [UNIQUEIDENTIFIER] NOT NULL,
	[LaboratoryId] [UNIQUEIDENTIFIER] NOT NULL,
	[Title] [NVARCHAR](255) NOT NULL,
 CONSTRAINT [PK_Ward] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [organization].[Department]    Script Date: 10/20/2022 12:47:08 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [organization].[Department](
	[Id] [UNIQUEIDENTIFIER] NOT NULL,
	[ParentId] [UNIQUEIDENTIFIER] NULL,
	[DepartmentTypeId] [INT] NOT NULL,
	[Title] [NVARCHAR](255) NOT NULL,
 CONSTRAINT [PK_Department] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [share].[BaseInfo]    Script Date: 10/20/2022 12:47:26 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [share].[BaseInfo](
	[Id] [INT] IDENTITY(1,1) NOT NULL,
	[BaseTableTypeId] [INT] NOT NULL,
	[Title] [NVARCHAR](255) NOT NULL,
 CONSTRAINT [PK_BaseInfo] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [share].[BaseTableType]    Script Date: 10/20/2022 12:47:50 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [share].[BaseTableType](
	[Id] [INT] NOT NULL,
	[Title] [NVARCHAR](255) NOT NULL,
 CONSTRAINT [PK_BaseTableType] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[User]  WITH CHECK ADD  CONSTRAINT [FK_User_BaseInfo] FOREIGN KEY([CountryId])
REFERENCES [share].[BaseInfo] ([Id])
GO

ALTER TABLE [dbo].[User] CHECK CONSTRAINT [FK_User_BaseInfo]
GO

ALTER TABLE [dbo].[User]  WITH CHECK ADD  CONSTRAINT [FK_User_BaseInfo1] FOREIGN KEY([CityId])
REFERENCES [share].[BaseInfo] ([Id])
GO

ALTER TABLE [dbo].[User] CHECK CONSTRAINT [FK_User_BaseInfo1]
GO

ALTER TABLE [dbo].[User]  WITH CHECK ADD  CONSTRAINT [FK_User_Department] FOREIGN KEY([DepartmentId])
REFERENCES [organization].[Department] ([Id])
GO

ALTER TABLE [dbo].[User] CHECK CONSTRAINT [FK_User_Department]
GO

ALTER TABLE [Lab].[Ability]  WITH CHECK ADD  CONSTRAINT [FK_Ability_Laboratory] FOREIGN KEY([LaboratoryId])
REFERENCES [Lab].[Laboratory] ([Id])
GO

ALTER TABLE [Lab].[Ability] CHECK CONSTRAINT [FK_Ability_Laboratory]
GO

ALTER TABLE [Lab].[Equipment]  WITH CHECK ADD  CONSTRAINT [FK_Equipment_BaseInfo] FOREIGN KEY([EquipmentTypeId])
REFERENCES [share].[BaseInfo] ([Id])
GO

ALTER TABLE [Lab].[Equipment] CHECK CONSTRAINT [FK_Equipment_BaseInfo]
GO

ALTER TABLE [Lab].[Equipment]  WITH CHECK ADD  CONSTRAINT [FK_Equipment_BaseInfo1] FOREIGN KEY([UsageTypeId])
REFERENCES [share].[BaseInfo] ([Id])
GO

ALTER TABLE [Lab].[Equipment] CHECK CONSTRAINT [FK_Equipment_BaseInfo1]
GO

ALTER TABLE [Lab].[Equipment]  WITH CHECK ADD  CONSTRAINT [FK_Equipment_BaseInfo2] FOREIGN KEY([CountryId])
REFERENCES [share].[BaseInfo] ([Id])
GO

ALTER TABLE [Lab].[Equipment] CHECK CONSTRAINT [FK_Equipment_BaseInfo2]
GO

ALTER TABLE [Lab].[Equipment]  WITH CHECK ADD  CONSTRAINT [FK_Equipment_BaseInfo3] FOREIGN KEY([SupplyTypeId])
REFERENCES [share].[BaseInfo] ([Id])
GO

ALTER TABLE [Lab].[Equipment] CHECK CONSTRAINT [FK_Equipment_BaseInfo3]
GO

ALTER TABLE [Lab].[Equipment]  WITH CHECK ADD  CONSTRAINT [FK_Equipment_Laboratory] FOREIGN KEY([LaboratoryId])
REFERENCES [Lab].[Laboratory] ([Id])
GO

ALTER TABLE [Lab].[Equipment] CHECK CONSTRAINT [FK_Equipment_Laboratory]
GO

ALTER TABLE [Lab].[Equipment]  WITH CHECK ADD  CONSTRAINT [FK_Equipment_Ward] FOREIGN KEY([WardId])
REFERENCES [Lab].[Ward] ([Id])
GO

ALTER TABLE [Lab].[Equipment] CHECK CONSTRAINT [FK_Equipment_Ward]
GO

ALTER TABLE [Lab].[EquipmentAbility]  WITH CHECK ADD  CONSTRAINT [FK_EquipmentAbility_Ability] FOREIGN KEY([AbilityId])
REFERENCES [Lab].[Ability] ([Id])
GO

ALTER TABLE [Lab].[EquipmentAbility] CHECK CONSTRAINT [FK_EquipmentAbility_Ability]
GO

ALTER TABLE [Lab].[EquipmentAbility]  WITH CHECK ADD  CONSTRAINT [FK_EquipmentAbility_Equipment] FOREIGN KEY([EquipmentId])
REFERENCES [Lab].[Equipment] ([Id])
GO

ALTER TABLE [Lab].[EquipmentAbility] CHECK CONSTRAINT [FK_EquipmentAbility_Equipment]
GO

ALTER TABLE [Lab].[Laboratory]  WITH CHECK ADD  CONSTRAINT [FK_Laboratory_BaseInfo] FOREIGN KEY([LaboratoryTypeId])
REFERENCES [share].[BaseInfo] ([Id])
GO

ALTER TABLE [Lab].[Laboratory] CHECK CONSTRAINT [FK_Laboratory_BaseInfo]
GO

ALTER TABLE [Lab].[Laboratory]  WITH CHECK ADD  CONSTRAINT [FK_Laboratory_BaseInfo1] FOREIGN KEY([PassiveDefenceId])
REFERENCES [share].[BaseInfo] ([Id])
GO

ALTER TABLE [Lab].[Laboratory] CHECK CONSTRAINT [FK_Laboratory_BaseInfo1]
GO

ALTER TABLE [Lab].[Laboratory]  WITH CHECK ADD  CONSTRAINT [FK_Laboratory_BaseInfo2] FOREIGN KEY([ApprovalAuthorityId])
REFERENCES [share].[BaseInfo] ([Id])
GO

ALTER TABLE [Lab].[Laboratory] CHECK CONSTRAINT [FK_Laboratory_BaseInfo2]
GO

ALTER TABLE [Lab].[Laboratory]  WITH CHECK ADD  CONSTRAINT [FK_Laboratory_Department] FOREIGN KEY([ResearchCenterId])
REFERENCES [organization].[Department] ([Id])
GO

ALTER TABLE [Lab].[Laboratory] CHECK CONSTRAINT [FK_Laboratory_Department]
GO

ALTER TABLE [Lab].[Ward]  WITH CHECK ADD  CONSTRAINT [FK_Ward_Laboratory] FOREIGN KEY([LaboratoryId])
REFERENCES [Lab].[Laboratory] ([Id])
GO

ALTER TABLE [Lab].[Ward] CHECK CONSTRAINT [FK_Ward_Laboratory]
GO

ALTER TABLE [organization].[Department]  WITH CHECK ADD  CONSTRAINT [FK_Department_BaseInfo] FOREIGN KEY([DepartmentTypeId])
REFERENCES [share].[BaseInfo] ([Id])
GO

ALTER TABLE [organization].[Department] CHECK CONSTRAINT [FK_Department_BaseInfo]
GO

ALTER TABLE [organization].[Department]  WITH CHECK ADD  CONSTRAINT [FK_Department_Department] FOREIGN KEY([ParentId])
REFERENCES [organization].[Department] ([Id])
GO

ALTER TABLE [organization].[Department] CHECK CONSTRAINT [FK_Department_Department]
GO

ALTER TABLE [share].[BaseInfo]  WITH CHECK ADD  CONSTRAINT [FK_BaseInfo_BaseTableType] FOREIGN KEY([BaseTableTypeId])
REFERENCES [share].[BaseTableType] ([Id])
GO

ALTER TABLE [share].[BaseInfo] CHECK CONSTRAINT [FK_BaseInfo_BaseTableType]
GO